const members = [
  {
    name: "김재현",
    englishName: "Kim Jae Hyeon",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 7,
      externalGiven: 20,
      internalReceived: 0,
      externalReceived: 17,
    },
    visitorsPerWeek: 0.19047619047619047,
    oneToOnePerWeek: 1.5714285714285714,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 15.0,
      avgVisitorPerWeek: 5.0,
      weeklyGoal: 5.0,
      trainingParticipation: 10.0,
      total: 80.0,
    },
  },
  {
    name: "강선미",
    englishName: "Kang sun-mi",
    attendance: {
      present: 20,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 31,
      externalGiven: 18,
      internalReceived: 0,
      externalReceived: 2,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 2.0,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 10.0,
      trainingParticipation: 10.0,
      total: 75.0,
    },
  },
  {
    name: "천종욱",
    englishName: "Cheong Jong-Ug",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 44,
      externalGiven: 24,
      internalReceived: 0,
      externalReceived: 5,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.7619047619047619,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 15.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 70.0,
    },
  },
  {
    name: "이성국",
    englishName: "Lee sungkuk",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 12,
      externalGiven: 30,
      internalReceived: 0,
      externalReceived: 0,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 1.7142857142857142,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 10.0,
      total: 70.0,
    },
  },
  {
    name: "유태영",
    englishName: "Yoo tae-young",
    attendance: {
      present: 19,
      absent: 0,
      late: 0,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 50,
      externalGiven: 6,
      internalReceived: 2,
      externalReceived: 4,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.5714285714285714,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 15.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 70.0,
    },
  },
  {
    name: "강성한",
    englishName: "Kang sunghan",
    attendance: {
      present: 19,
      absent: 0,
      late: 0,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 26,
      externalGiven: 7,
      internalReceived: 10,
      externalReceived: 3,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.7142857142857142,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 5.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 10.0,
      total: 65.0,
    },
  },
  {
    name: "김태민",
    englishName: "Kim Tae-Min",
    attendance: {
      present: 20,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 19,
      externalGiven: 9,
      internalReceived: 3,
      externalReceived: 8,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.3333333333333333,
    scores: {
      absenteeism: 10.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 60.0,
    },
  },
  {
    name: "남장우",
    englishName: "Nam jangwoo",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 15,
      externalGiven: 16,
      internalReceived: 5,
      externalReceived: 20,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.0476190476190477,
    scores: {
      absenteeism: 15.0,
      punctuality: 5.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 60.0,
    },
  },
  {
    name: "박진희",
    englishName: "JENNIE PARK",
    attendance: {
      present: 20,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 12,
      externalGiven: 14,
      internalReceived: 0,
      externalReceived: 3,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 0.9523809523809523,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 5.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 5.0,
      total: 55.0,
    },
  },
  {
    name: "이진우",
    englishName: "Lee Jin Woo",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 49,
      externalGiven: 0,
      internalReceived: 6,
      externalReceived: 10,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.8571428571428571,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 5.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 5.0,
      total: 55.0,
    },
  },
  {
    name: "이로운",
    englishName: "Lee roun",
    attendance: {
      present: 11,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 11,
      externalGiven: 7,
      internalReceived: 5,
      externalReceived: 2,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.7272727272727273,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 55.0,
    },
  },
  {
    name: "이윤재",
    englishName: "Lee yoonjae",
    attendance: {
      present: 17,
      absent: 1,
      late: 1,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 49,
      externalGiven: 6,
      internalReceived: 0,
      externalReceived: 11,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.9047619047619048,
    scores: {
      absenteeism: 10.0,
      punctuality: 5.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 15.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 5.0,
      total: 55.0,
    },
  },
  {
    name: "문진숙",
    englishName: "Moon jinsuk",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 15,
      externalGiven: 7,
      internalReceived: 25,
      externalReceived: 14,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 1.3333333333333333,
    scores: {
      absenteeism: 15.0,
      punctuality: 5.0,
      referralsPerWeek: 15.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 55.0,
    },
  },
  {
    name: "오춘택",
    englishName: "O Chun-Taek",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 20,
      externalGiven: 7,
      internalReceived: 0,
      externalReceived: 10,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.2857142857142858,
    scores: {
      absenteeism: 15.0,
      punctuality: 5.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 10.0,
      total: 55.0,
    },
  },
  {
    name: "신정준",
    englishName: "Shin jeongjun",
    attendance: {
      present: 18,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 3,
    },
    referrals: {
      internalGiven: 54,
      externalGiven: 2,
      internalReceived: 19,
      externalReceived: 9,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.7619047619047619,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 10.0,
      total: 55.0,
    },
  },
  {
    name: "성현기",
    englishName: "Sung hyeongi",
    attendance: {
      present: 20,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 1,
      externalGiven: 75,
      internalReceived: 2,
      externalReceived: 10,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.9523809523809523,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 0.0,
      total: 55.0,
    },
  },
  {
    name: "윤선행",
    englishName: "youn sun hang",
    attendance: {
      present: 19,
      absent: 0,
      late: 2,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 13,
      externalGiven: 29,
      internalReceived: 0,
      externalReceived: 4,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 1.7142857142857142,
    scores: {
      absenteeism: 15.0,
      punctuality: 0.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 55.0,
    },
  },
  {
    name: "최득남",
    englishName: "Choi duknam",
    attendance: {
      present: 18,
      absent: 0,
      late: 0,
      sick: 3,
      proxy: 0,
    },
    referrals: {
      internalGiven: 35,
      externalGiven: 1,
      internalReceived: 1,
      externalReceived: 2,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.6666666666666666,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 5.0,
      total: 50.0,
    },
  },
  {
    name: "정환영",
    englishName: "Jung hwan young",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 13,
      externalGiven: 7,
      internalReceived: 0,
      externalReceived: 12,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.380952380952381,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 10.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 10.0,
      total: 50.0,
    },
  },
  {
    name: "목영만",
    englishName: "Mok young-man",
    attendance: {
      present: 18,
      absent: 2,
      late: 0,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 26,
      externalGiven: 5,
      internalReceived: 41,
      externalReceived: 14,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.42857142857142855,
    scores: {
      absenteeism: 5.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 10.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 5.0,
      total: 50.0,
    },
  },
  {
    name: "오도영",
    englishName: "Oh doyoung",
    attendance: {
      present: 20,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 47,
      externalGiven: 3,
      internalReceived: 0,
      externalReceived: 2,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 0.38095238095238093,
    scores: {
      absenteeism: 10.0,
      punctuality: 10.0,
      referralsPerWeek: 20.0,
      thankYouContribution: 5.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 0.0,
      total: 45.0,
    },
  },
  {
    name: "우주엽",
    englishName: "Woo  joo yeop",
    attendance: {
      present: 11,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 2,
      externalGiven: 5,
      internalReceived: 0,
      externalReceived: 5,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.1818181818181819,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 5.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 10.0,
      total: 45.0,
    },
  },
  {
    name: "변정아",
    englishName: "Byun junga",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 5,
      externalGiven: 7,
      internalReceived: 1,
      externalReceived: 11,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.6666666666666666,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 5.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 10.0,
      total: 40.0,
    },
  },
  {
    name: "이승희",
    englishName: "Lee seunghee",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 9,
      externalGiven: 6,
      internalReceived: 0,
      externalReceived: 8,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.380952380952381,
    scores: {
      absenteeism: 15.0,
      punctuality: 5.0,
      referralsPerWeek: 5.0,
      thankYouContribution: 5.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 0.0,
      total: 35.0,
    },
  },
  {
    name: "최상봉",
    englishName: "Sangbong Choi",
    attendance: {
      present: 16,
      absent: 1,
      late: 2,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 5,
      externalGiven: 12,
      internalReceived: 0,
      externalReceived: 5,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 1.0952380952380953,
    scores: {
      absenteeism: 10.0,
      punctuality: 0.0,
      referralsPerWeek: 10.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 5.0,
      trainingParticipation: 5.0,
      total: 30.0,
    },
  },
  {
    name: "강성신",
    englishName: "Kang sungshin",
    attendance: {
      present: 11,
      absent: 0,
      late: 0,
      sick: 10,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 3,
      internalReceived: 3,
      externalReceived: 9,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.5714285714285714,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 0.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 0.0,
      total: 25.0,
    },
  },
  {
    name: "김근호",
    englishName: "KIm kunho",
    attendance: {
      present: 20,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 3,
      externalGiven: 7,
      internalReceived: 2,
      externalReceived: 5,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.8095238095238095,
    scores: {
      absenteeism: 10.0,
      punctuality: 10.0,
      referralsPerWeek: 0.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 5.0,
      total: 25.0,
    },
  },
  {
    name: "박은정",
    englishName: "Park eunjung",
    attendance: {
      present: 1,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 0,
      internalReceived: 0,
      externalReceived: 0,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.0,
    scores: {
      absenteeism: 15.0,
      punctuality: 10.0,
      referralsPerWeek: 0.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 0.0,
      total: 25.0,
    },
  },
  {
    name: "윤지환",
    englishName: "Yoon jihwan",
    attendance: {
      present: 9,
      absent: 1,
      late: 0,
      sick: 1,
      proxy: 2,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 1,
      internalReceived: 0,
      externalReceived: 3,
    },
    visitorsPerWeek: 0.0,
    oneToOnePerWeek: 0.8461538461538461,
    scores: {
      absenteeism: 10.0,
      punctuality: 10.0,
      referralsPerWeek: 0.0,
      thankYouContribution: 0.0,
      avgVisitorPerWeek: 0.0,
      weeklyGoal: 0.0,
      trainingParticipation: 0.0,
      total: 20.0,
    },
  },
  {
    name: "비지터",
    englishName: NaN,
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 0,
      internalReceived: 0,
      externalReceived: 0,
    },
    visitorsPerWeek: NaN,
    oneToOnePerWeek: NaN,
    scores: {
      absenteeism: NaN,
      punctuality: NaN,
      referralsPerWeek: NaN,
      thankYouContribution: NaN,
      avgVisitorPerWeek: NaN,
      weeklyGoal: NaN,
      trainingParticipation: NaN,
      total: NaN,
    },
  },
  {
    name: "BNI",
    englishName: NaN,
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 1,
      internalReceived: 3,
      externalReceived: 5,
    },
    visitorsPerWeek: NaN,
    oneToOnePerWeek: NaN,
    scores: {
      absenteeism: NaN,
      punctuality: NaN,
      referralsPerWeek: NaN,
      thankYouContribution: NaN,
      avgVisitorPerWeek: NaN,
      weeklyGoal: NaN,
      trainingParticipation: NaN,
      total: NaN,
    },
  },
  {
    name: "합",
    englishName: NaN,
    attendance: {
      present: 534,
      absent: 12,
      late: 9,
      sick: 22,
      proxy: 9,
    },
    referrals: {
      internalGiven: 592,
      externalGiven: 337,
      internalReceived: 130,
      externalReceived: 222,
    },
    visitorsPerWeek: NaN,
    oneToOnePerWeek: NaN,
    scores: {
      absenteeism: NaN,
      punctuality: NaN,
      referralsPerWeek: NaN,
      thankYouContribution: NaN,
      avgVisitorPerWeek: NaN,
      weeklyGoal: NaN,
      trainingParticipation: NaN,
      total: NaN,
    },
  },
];

export default members;
