const members = [
  {
    name: "김재현",
    englishName: "Kim Jae Hyeon",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 6,
      externalGiven: 37,
      internalReceived: 0,
      externalReceived: 15,
    },
    visitorsPerWeek: 0.2857142857142857,
    oneToOnePerWeek: 1.4761904761904763,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 15,
      avgVisitorPerWeek: 10,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 85,
    },
  },
  {
    name: "유태영",
    englishName: "Yoo tae-young",
    attendance: {
      present: 19,
      absent: 0,
      late: 0,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 50,
      externalGiven: 5,
      internalReceived: 2,
      externalReceived: 4,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1.3333333333333333,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 15,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 75,
    },
  },
  {
    name: "천종욱",
    englishName: "Cheong Jong-Ug",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 37,
      externalGiven: 18,
      internalReceived: 0,
      externalReceived: 5,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1.5238095238095237,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 15,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 0,
      total: 65,
    },
  },
  {
    name: "강선미",
    englishName: "Kang sun-mi",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 29,
      externalGiven: 14,
      internalReceived: 0,
      externalReceived: 4,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.9523809523809523,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 5,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 65,
    },
  },
  {
    name: "강성한",
    englishName: "Kang sunghan",
    attendance: {
      present: 19,
      absent: 0,
      late: 0,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 25,
      externalGiven: 4,
      internalReceived: 10,
      externalReceived: 2,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1.7142857142857142,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 5,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 65,
    },
  },
  {
    name: "이성국",
    englishName: "Lee sungkuk",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 14,
      externalGiven: 23,
      internalReceived: 0,
      externalReceived: 1,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 1.7142857142857142,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 10,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 65,
    },
  },
  {
    name: "윤선행",
    englishName: "youn sun hang",
    attendance: {
      present: 19,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 17,
      externalGiven: 23,
      internalReceived: 0,
      externalReceived: 5,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 1.4285714285714286,
    scores: {
      absenteeism: 15,
      punctuality: 5,
      referralsPerWeek: 20,
      thankYouContribution: 10,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 65,
    },
  },
  {
    name: "이진우",
    englishName: "Lee Jin Woo",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 41,
      externalGiven: 1,
      internalReceived: 3,
      externalReceived: 6,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.7142857142857143,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 5,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 10,
      total: 60,
    },
  },
  {
    name: "이윤재",
    englishName: "Lee yoonjae",
    attendance: {
      present: 17,
      absent: 1,
      late: 0,
      sick: 3,
      proxy: 0,
    },
    referrals: {
      internalGiven: 44,
      externalGiven: 7,
      internalReceived: 0,
      externalReceived: 11,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.8571428571428571,
    scores: {
      absenteeism: 10,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 15,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 5,
      total: 60,
    },
  },
  {
    name: "문진숙",
    englishName: "Moon jinsuk",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 17,
      externalGiven: 6,
      internalReceived: 24,
      externalReceived: 12,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 1.0952380952380953,
    scores: {
      absenteeism: 15,
      punctuality: 5,
      referralsPerWeek: 15,
      thankYouContribution: 15,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 60,
    },
  },
  {
    name: "성현기",
    englishName: "Sung hyeongi",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 1,
      externalGiven: 68,
      internalReceived: 2,
      externalReceived: 12,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.8571428571428571,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 15,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 0,
      total: 60,
    },
  },
  {
    name: "김태민",
    englishName: "Kim Tae-Min",
    attendance: {
      present: 20,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 17,
      externalGiven: 9,
      internalReceived: 1,
      externalReceived: 10,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.1904761904761905,
    scores: {
      absenteeism: 10,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 5,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 55,
    },
  },
  {
    name: "이로운",
    englishName: "Lee roun",
    attendance: {
      present: 7,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 7,
      externalGiven: 4,
      internalReceived: 1,
      externalReceived: 0,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1.1428571428571428,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 55,
    },
  },
  {
    name: "목영만",
    englishName: "Mok young-man",
    attendance: {
      present: 19,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 36,
      externalGiven: 7,
      internalReceived: 41,
      externalReceived: 15,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.42857142857142855,
    scores: {
      absenteeism: 10,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 10,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 5,
      total: 55,
    },
  },
  {
    name: "오도영",
    englishName: "Oh doyoung",
    attendance: {
      present: 20,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 49,
      externalGiven: 2,
      internalReceived: 0,
      externalReceived: 4,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 0.42857142857142855,
    scores: {
      absenteeism: 10,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 15,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 0,
      total: 55,
    },
  },
  {
    name: "신정준",
    englishName: "Shin jeongjun",
    attendance: {
      present: 18,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 3,
    },
    referrals: {
      internalGiven: 52,
      externalGiven: 3,
      internalReceived: 18,
      externalReceived: 8,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.5714285714285714,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 10,
      total: 55,
    },
  },
  {
    name: "최득남",
    englishName: "Choi duknam",
    attendance: {
      present: 19,
      absent: 0,
      late: 0,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 35,
      externalGiven: 1,
      internalReceived: 1,
      externalReceived: 1,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.47619047619047616,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 20,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 5,
      total: 50,
    },
  },
  {
    name: "박진희",
    englishName: "JENNIE PARK",
    attendance: {
      present: 19,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 2,
    },
    referrals: {
      internalGiven: 9,
      externalGiven: 13,
      internalReceived: 0,
      externalReceived: 2,
    },
    visitorsPerWeek: 0.09523809523809523,
    oneToOnePerWeek: 0.7619047619047619,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 15,
      thankYouContribution: 5,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 5,
      total: 50,
    },
  },
  {
    name: "정환영",
    englishName: "Jung hwan young",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 12,
      externalGiven: 4,
      internalReceived: 0,
      externalReceived: 10,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.380952380952381,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 10,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 50,
    },
  },
  {
    name: "우주엽",
    englishName: "Woo  joo yeop",
    attendance: {
      present: 7,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 1,
      externalGiven: 5,
      internalReceived: 0,
      externalReceived: 1,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1.2857142857142858,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 10,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 10,
      total: 50,
    },
  },
  {
    name: "남장우",
    englishName: "Nam jangwoo",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 14,
      externalGiven: 15,
      internalReceived: 8,
      externalReceived: 21,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.8095238095238095,
    scores: {
      absenteeism: 15,
      punctuality: 5,
      referralsPerWeek: 20,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 5,
      total: 45,
    },
  },
  {
    name: "오춘택",
    englishName: "O Chun-Taek",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 15,
      externalGiven: 7,
      internalReceived: 0,
      externalReceived: 8,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.0476190476190477,
    scores: {
      absenteeism: 15,
      punctuality: 5,
      referralsPerWeek: 15,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 45,
    },
  },
  {
    name: "변정아",
    englishName: "Byun junga",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 6,
      externalGiven: 5,
      internalReceived: 1,
      externalReceived: 12,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.7619047619047619,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 5,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 10,
      total: 40,
    },
  },
  {
    name: "김근호",
    englishName: "KIm kunho",
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 1,
      externalGiven: 7,
      internalReceived: 0,
      externalReceived: 6,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 0,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 35,
    },
  },
  {
    name: "이승희",
    englishName: "Lee seunghee",
    attendance: {
      present: 20,
      absent: 0,
      late: 1,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 8,
      externalGiven: 6,
      internalReceived: 0,
      externalReceived: 10,
    },
    visitorsPerWeek: 0.047619047619047616,
    oneToOnePerWeek: 1.1904761904761905,
    scores: {
      absenteeism: 15,
      punctuality: 5,
      referralsPerWeek: 5,
      thankYouContribution: 5,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 0,
      total: 35,
    },
  },
  {
    name: "최상봉",
    englishName: "Sangbong Choi",
    attendance: {
      present: 16,
      absent: 0,
      late: 2,
      sick: 2,
      proxy: 0,
    },
    referrals: {
      internalGiven: 4,
      externalGiven: 11,
      internalReceived: 0,
      externalReceived: 4,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1,
    scores: {
      absenteeism: 15,
      punctuality: 0,
      referralsPerWeek: 10,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 5,
      total: 35,
    },
  },
  {
    name: "강성신",
    englishName: "Kang sungshin",
    attendance: {
      present: 15,
      absent: 0,
      late: 0,
      sick: 6,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 3,
      internalReceived: 4,
      externalReceived: 8,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 0.7619047619047619,
    scores: {
      absenteeism: 15,
      punctuality: 10,
      referralsPerWeek: 0,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 0,
      trainingParticipation: 0,
      total: 25,
    },
  },
  {
    name: "윤지환",
    englishName: "Yoon jihwan",
    attendance: {
      present: 7,
      absent: 1,
      late: 0,
      sick: 0,
      proxy: 1,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 1,
      internalReceived: 0,
      externalReceived: 2,
    },
    visitorsPerWeek: 0,
    oneToOnePerWeek: 1,
    scores: {
      absenteeism: 10,
      punctuality: 10,
      referralsPerWeek: 0,
      thankYouContribution: 0,
      avgVisitorPerWeek: 0,
      weeklyGoal: 5,
      trainingParticipation: 0,
      total: 25,
    },
  },
  {
    name: "비지터",
    englishName: NaN,
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 0,
      internalReceived: 0,
      externalReceived: 0,
    },
    visitorsPerWeek: NaN,
    oneToOnePerWeek: NaN,
    scores: {
      absenteeism: NaN,
      punctuality: NaN,
      referralsPerWeek: NaN,
      thankYouContribution: NaN,
      avgVisitorPerWeek: NaN,
      weeklyGoal: NaN,
      trainingParticipation: NaN,
      total: NaN,
    },
  },
  {
    name: "BNI",
    englishName: NaN,
    attendance: {
      present: 21,
      absent: 0,
      late: 0,
      sick: 0,
      proxy: 0,
    },
    referrals: {
      internalGiven: 0,
      externalGiven: 0,
      internalReceived: 3,
      externalReceived: 7,
    },
    visitorsPerWeek: NaN,
    oneToOnePerWeek: NaN,
    scores: {
      absenteeism: NaN,
      punctuality: NaN,
      referralsPerWeek: NaN,
      thankYouContribution: NaN,
      avgVisitorPerWeek: NaN,
      weeklyGoal: NaN,
      trainingParticipation: NaN,
      total: NaN,
    },
  },
  {
    name: "합",
    englishName: NaN,
    attendance: {
      present: 540,
      absent: 10,
      late: 7,
      sick: 18,
      proxy: 9,
    },
    referrals: {
      internalGiven: 572,
      externalGiven: 314,
      internalReceived: 123,
      externalReceived: 219,
    },
    visitorsPerWeek: NaN,
    oneToOnePerWeek: NaN,
    scores: {
      absenteeism: NaN,
      punctuality: NaN,
      referralsPerWeek: NaN,
      thankYouContribution: NaN,
      avgVisitorPerWeek: NaN,
      weeklyGoal: NaN,
      trainingParticipation: NaN,
      total: NaN,
    },
  },
];

export default members;
